SELECT CONCAT('/home/grep/src/', CONCAT(B.BOARD_ID, CONCAT('/', CONCAT(F.FILE_ID, CONCAT(F.FILE_NAME, F.FILE_EXT))))) AS FILE_PATH
FROM USED_GOODS_BOARD B 
JOIN USED_GOODS_FILE F  ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS)
                FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC                